name: Deploy Node.js Docker App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cp /root/firewall-ambientes/FirewallManager-Backend-prod/.env /root/env_backup
          
          mkdir -p /root/temp_api
          
          git clone https://${{ secrets.GIT_USERNAME }}:${{ secrets.GIT_TOKEN }}@github.com/Hostly-Network/Backend-FirewallOVH-APIREST.git /root/temp_api
          
          cd /root/temp_api
          rm -f .env
          cp -r * /root/firewall-ambientes/FirewallManager-Backend-prod/
          
          cp /root/env_backup /root/firewall-ambientes/FirewallManager-Backend-prod/.env
          
          rm -rf /root/temp_api
          rm /root/env_backup
          
          cd /root/firewall-ambientes/FirewallManager-Backend-prod
          docker compose stop api
          docker compose up -d --build
          
          # Limpiar imágenes no utilizadas
          docker image prune -f --filter "label!=db"
